// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// c_iso_sum
NumericVector c_iso_sum(NumericMatrix x, NumericVector t, NumericVector sl, double taper_a);
RcppExport SEXP _pppgram_c_iso_sum(SEXP xSEXP, SEXP tSEXP, SEXP slSEXP, SEXP taper_aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sl(slSEXP);
    Rcpp::traits::input_parameter< double >::type taper_a(taper_aSEXP);
    rcpp_result_gen = Rcpp::wrap(c_iso_sum(x, t, sl, taper_a));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pppgram_c_iso_sum", (DL_FUNC) &_pppgram_c_iso_sum, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_pppgram(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
